WhaleMarket/whale_market

src/api/axios.js, src/components/join/joinMember/JoinMember.jsx, src/components/main/chat/ChatProfileHeader.jsx, src/context/AuthProvider.js, src/index.js, src/pages/login_page/EmailLogin.jsx
- 이메일 로그인 가입된 이메일 검증 후 로그인 성공 기능
- 잘못된 이메일 및 비밀번호 입력 시 에러메시지 나타나는 기능
- 이유: 유저의 로그인 정보가 전역에서 관리되어야 할 필요성이 있기 때문에 context 폴더를 생성해서 AuthProvider.js 파일에 전역 context 역할을 하는 AuthProvider을 만들어 App 컴포넌트를 감싸주었습니다. 이메일과 패스워드를 contex의 데이터로 넣었습니다.
- 작업 내역: axios로 로그인 요청 후 이메일 및 비밀번호 검증 후 로그인을 승인하여 main/home으로 페이지 전환되는 기능 추가
- 동작 
<div align=center>
</div>
=> Whale login

src/components/main/HomeSection.jsx, src/components/main/Homeheader.jsx, src/components/main/homeSearch/GoBackBtn.jsx, src/components/main/homeSearch/SearchBar.jsx, src/pages/main_page/HomeSearch.jsx, src/routes/Main.jsx
- 홈 화면에서 계정 검색 화면으로 이동 및 뒤로 가기 구현
=> Whale search

src/components/main/posting/postingheader/Upload_btn.jsx, src/components/main/posting/postingsection/Textarea.jsx, src/context/UploadProvider.js, src/pages/main_page/Posting.jsx
- 이유
context 전역 상태 관리를 따로 파일로 만들어 관리하는 게  좋기 때문에 새롭게 파일을 만들어 리팩토링 해주었습니다.
- 작업 내역 
UploadProvider.js 생성, 이로 인해 생기는 파일 경로 변경
=> Whale posting

src/components/main/mainProfile/ProfileEditHeader.jsx, src/components/main/mainProfile/ProfileEditSection.jsx, src/components/profile/ProfileForm.jsx, src/components/profile/StartButton.jsx, src/components/profile/index.jsx, src/pages/main_page/mainProfile/ProfileEdit.jsx
=> Whale main profile2

src/components/splash/Splash.jsx
=> Whale splash

src/App.js, src/components/emaillogin/LoginForm/index.jsx, src/components/emaillogin/button/Button.jsx, src/components/join/JoinForm/index.jsx, src/components/join/JoinForm/index.style.js, src/components/main/Navbar.jsx, src/components/main/mainProfile/productUpload/productDetailUpload/Detail.jsx, src/components/profile/ProfileForm.jsx, src/pages/login_page/EmailLogin.jsx, src/pages/login_page/Join.jsx, src/pages/login_page/Login.jsx, src/pages/login_page/Profile.jsx, src/pages/main_page/chat/ChattingView.jsx, src/routes/Main.jsx
- 글로벌 스타일에 히든 클래스 추가(a11yhidden)
- 함수 컴포넌트명 변경(Test -> MainRouter)
=> Whale small

src/App.js, src/components/main/chat/chatContents/index.jsx, src/components/main/chat/chatForm/index.jsx, src/components/main/chat/chatForm/index.style.js, src/pages/main_page/chat/ChattingView.jsx
- 이유: 채팅 Contents UI 구현을 위한 수정입니다.
=> Whale chatting2

src/components/main/HomeSection.jsx, src/components/main/Homeheader.jsx, src/components/main/Navbar.jsx, src/routes/Main.jsx
- 이유
navBar 에서 경로 인식 못하는 문제 수정
=> :truck: HomeSearch 페이지 경로 수정

src/routes/Main.jsx
- 이유: 코드 리팩토링으로 필요없는 코드 삭제합니다.
=> 🔥 location 관련 코드 삭제

src/components/main/mainProfile/productUpload/productDetailUpload/Detail.jsx, src/components/main/mainProfile/productUpload/productImgUpload/Upload_btn.jsx, src/components/main/mainProfile/productUpload/productUploadHeader/Save_btn.jsx, src/components/main/posting/imageuploadbutton/index.jsx
=> :sparkels: 이미지 용량 제한, 숫자 0 예외처리

public/index.html, src/Portal.js, src/components/main/ChatProfileHeader.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/modal/AlertModal.jsx, src/components/modal/Modal.jsx, src/components/modal/ModalBtn.jsx
- 작업 내역 
- 기본 슬라이드 모달 및 alert 모달 구현
- 동작
=> Whale modal

src/components/emaillogin/LoginForm/index.jsx, src/components/join/JoinForm/index.jsx, src/components/main/mainProfile/follow/FollowCard.jsx, src/components/main/mainProfile/follow/User.jsx, src/components/main/mainProfile/follow/UserFollowButton.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/modal/Modal.jsx, src/components/profile/ProfileForm.jsx, src/context/AuthProvider.js, src/hook/useAccountInfo.js, src/routes/Main.jsx
=> :recycle: useState 초기 값 한 곳으로 모아서 객체화

src/components/main/mainProfile/productUpload/productUploadHeader/Save_btn.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/mainProfile/user_profile/ProductSection.jsx, src/components/main/posting/postingheader/Upload_btn.jsx, src/context/AuthProvider.js, src/hook/useAccountInfo.js, src/hook/useProductInfo.js, src/pages/main_page/mainProfile/MyProfile.jsx, src/routes/Main.jsx
=> Whale posting axios

src/components/main/homeFeed/FeedContent.jsx, src/components/main/homeFeed/IconGroup.jsx, src/components/main/homeFeed/ProfileSection.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/mainProfile/user_profile/PostSection.jsx, src/components/main/mainProfile/user_profile/ProductSection.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx
=> :lipstick: 피드 화면, 프로필 화면 UI 수정

src/components/main/homeFeed/FeedContent.jsx, src/components/main/mainProfile/productUpload/productDetailUpload/Detail.jsx, src/components/main/mainProfile/productUpload/productDetailUpload/DetailInput.jsx, src/components/main/mainProfile/productUpload/productUploadHeader/Save_btn.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/mainProfile/user_profile/PostIconContainer.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/mainProfile/user_profile/ProductSection.jsx, src/components/main/postDetail/Comment.jsx, src/components/main/postDetail/CommentInput.jsx, src/components/main/postDetail/PostContent.jsx, src/components/main/postDetail/PostModal.jsx, src/components/modal/AlertModal.jsx, src/components/modal/Modal.jsx
=> Whale profile comment

src/components/main/Navbar.jsx, src/components/main/mainProfile/follow/FollowUser.jsx, src/components/main/mainProfile/user_profile/PostSection.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/mainProfile/user_profile/ProductSection.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/main/mainProfile/user_profile/UserProfileSection.jsx, src/context/AuthProvider.js, src/pages/main_page/mainProfile/MyProfile.jsx, src/routes/Main.jsx
=> Whale user profile

src/components/main/mainProfile/user_profile/ProductCard.jsx
=> Whale product del

src/components/main/mainProfile/user_profile/PostSection.jsx, src/components/main/mainProfile/user_profile/ProductSection.jsx, src/components/main/postDetail/CommentInput.jsx, src/hook/useAccountInfo.js, src/pages/main_page/HomeSearch.jsx, src/pages/main_page/mainProfile/Followers.jsx, src/pages/main_page/mainProfile/Following.jsx
=> Whale limit

src/components/main/mainProfile/productUpload/productDetailUpload/Detail.jsx, src/components/main/mainProfile/productUpload/productDetailUpload/DetailInput.jsx, src/components/main/mainProfile/productUpload/productImgUpload/Upload_btn.jsx, src/components/main/mainProfile/productUpload/productImgUpload/Upload_section.jsx, src/components/main/mainProfile/productUpload/productUploadHeader/Edit_btn.jsx, src/components/main/mainProfile/productUpload/productUploadHeader/index.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/context/ProductModification.js, src/pages/main_page/mainProfile/ProductEdit.jsx, src/routes/Main.jsx
=> :sparkles: 상품 수정 기능 추가

src/components/main/homeFeed/IconGroup.jsx, src/components/main/mainProfile/user_profile/PostIconContainer.jsx, src/components/main/postDetail/CommentInput.jsx, src/components/main/postDetail/PostContent.jsx, src/components/main/postDetail/PostModal.jsx, src/components/main/posting/postingsection/Textarea.jsx, src/pages/main_page/Posting.jsx, src/pages/main_page/mainProfile/PostingEdit.jsx
=> Whale ranking

src/components/main/Homeheader.jsx, src/components/main/market/reward.jsx, src/components/main/postDetail/CommentInput.jsx, src/components/main/posting/postingsection/Profile.jsx, src/routes/Main.jsx
- 로그인 후 token이 있어야 main/home 로 진입할 수 있게 수정
- /search => home/search 경로 수정
- err 오탈자 수정(=> error)
- 게시물 작성 시 로그인 사용자의 프로필 사진 불러오기
=> Whale small2

src/components/main/ChatProfileHeader.jsx, src/components/main/Navbar.jsx, src/components/main/homeFeed/IconGroup.jsx, src/components/main/homeFeed/ProfileSection.jsx, src/components/main/mainProfile/follow/FollowerUser.jsx, src/components/main/mainProfile/follow/FollowingUser.jsx, src/components/main/mainProfile/user_profile/PostIconContainer.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/mainProfile/user_profile/ProductSection.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/main/market/Ranking.jsx, src/components/main/market/Reward.jsx, src/components/main/market/index.jsx, src/components/splash/Splash.jsx, src/theme/heartClickEvent.js, src/theme/marquee.js, src/theme/nabvarClickEvent.js, src/theme/splashEvent.js
=> 자잘한 기능들 추가

src/components/main/Navbar.jsx
=> :truck: reward 경로 수정

src/components/main/Navbar.jsx
=> :adhesive_bandage: 충돌으로 인한 코드 수정

src/components/main/Homeheader.jsx, src/components/main/market/Ranking.jsx, src/components/main/postDetail/CommentInput.jsx, src/components/main/postDetail/PostContent.jsx
=> Whale weather

src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/modal/QuoteModal.jsx
=> :lipstick: 인용구 모달 추가

src/components/main/Homeheader.jsx, src/components/main/mainProfile/follow/FollowerUser.jsx, src/components/main/mainProfile/follow/FollowingUser.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/main/market/Ranking.jsx, src/components/modal/QuoteModal.jsx
=> Whale quote

.prettierrc, src/components/emaillogin/LoginForm/index.style.js, src/components/join/JoinForm/index.jsx, src/components/join/JoinForm/index.style.js, src/components/main/homeFeed/FeedContent.jsx, src/components/main/homeFeed/ProfileSection.jsx, src/components/main/mainProfile/profile_edit/ProfileEditForm.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/market/Ranking.jsx, src/components/profile/ProfileForm.jsx, src/pages/main_page/Reward.jsx
- reward 로딩 페이지 추가
- 프리티어 파일 추가
=> Whale profile edit

src/components/main/homeFeed/FeedContent.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/market/index.jsx, src/components/main/postDetail/Comment.jsx, src/components/main/postDetail/PostContent.jsx
=> :lipstick: 반응형 수정

src/components/main/mainProfile/productUpload/productUploadHeader/Edit_btn.jsx, src/components/main/mainProfile/productUpload/productUploadHeader/Save_btn.jsx, src/components/main/mainProfile/profile_edit/profileEditHeader/Edit_btn.jsx, src/components/main/mainProfile/user_profile/PostCard.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/posting/postingheader/Edit_btn.jsx, src/components/main/posting/postingheader/Upload_btn.jsx
=> :fire: alert 삭제

src/components/main/mainProfile/user_profile/AlbumReward.jsx, src/components/main/mainProfile/user_profile/PostSection.jsx, src/components/main/market/index.jsx
=> :lipstick: 반응형 값 수정

src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/main/market/Ranking.jsx, src/components/main/market/Reward.jsx, src/components/main/market/index.jsx, src/components/main/postDetail/PostContent.jsx, src/components/main/postDetail/PostModal.jsx, src/components/main/posting/postingheader/Upload_btn.jsx, src/components/main/posting/postingsection/CancleBtn.jsx, src/components/main/posting/postingsection/ImgArticle.jsx, src/components/main/posting/postingsection/PostingImg.jsx, src/components/main/posting/postingsection/Profile.jsx, src/components/main/posting/postingsection/Textarea.jsx, src/components/main/posting/postingsection/index.jsx, src/components/splash/Splash.jsx
- 스플래시 로고 위치 값 수정
- 게시물 작성 페이지 반응형 추가
- 프로필 페이지 팔로잉 팔로워 위치 조정
- 리워드 페이지 반응형 값 수정
=> Whale extra

src/components/main/postDetail/Comment.jsx
=> :lipstick: 댓글 스타일 값 수정

README.md, src/components/main/mainProfile/user_profile/UserProfileContents.jsx
=> :lipstick: 반응형 페이지 수정 및 리드미 수정

src/components/main/mainProfile/user_profile/UserProfileContents.jsx
=> :pencil2: 에러 수정

src/components/main/HomeSection.jsx, src/hook/useAccountInfo.js
=> :recycle: feedloading 구현

src/components/main/Homeheader.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/main/market/Ranking.jsx, src/components/main/market/index.jsx
=> :lipstick: 반응형 값 수정, 프로필 문구 수정

src/components/main/Homeheader.jsx, src/components/main/mainProfile/follow/FollowerUser.jsx, src/components/main/mainProfile/follow/FollowingUser.jsx
=> Whale check

public/index.html, src/components/main/mainProfile/productUpload/productDetailUpload/Detail.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/main/posting/imageuploadbutton/index.jsx
=> :lipstick: 마지막 수정

src/App.js, src/components/modal/AlertModal.jsx, src/components/modal/Modal.jsx
=> 🩹 css 구현 최종 적용

src/components/main/homeFeed/FeedContent.jsx, src/components/main/homeFeed/IconGroup.jsx, src/components/main/mainProfile/user_profile/PostIconContainer.jsx, src/components/main/postDetail/CommentInput.jsx, src/components/main/postDetail/PostContent.jsx, src/components/main/postDetail/PostModal.jsx
=> :sparkles: whaleGM 계정에 댓글 못 달게 막았음

README.md
=> :memo: 리드미 프로젝트 설명서 추가

README.md, src/components/main/HomeSection.jsx, src/components/main/mainProfile/follow/FollowerUser.jsx, src/components/main/mainProfile/follow/FollowingUser.jsx, src/components/main/mainProfile/productUpload/productDetailUpload/Detail.jsx, src/components/main/mainProfile/user_profile/ProductCard.jsx, src/components/main/mainProfile/user_profile/UserProfileContents.jsx, src/components/profile/ProfileForm.jsx
=> :lipstick: 리드미 및 해결 안 된 오류 해결
